### ISSUE TITLE
Can I use Hetu to create a REPL for SciDart?

### ISSUE THREAD

**Issue by polotto** [hetu-script/hetu-script#44]
Amazing project, congratulations! It's fit all my needs!

I have been searching for some interpreter written in Dart and so far your language is the best that merge well Dart and Script language.
I created a library called SciDart(https://scidart.org/) my intention is create a full and functional Scientific platform for Dart and to achieve this I need a script language interpreter. Can I use Hetu as SciDart script language?

**Comment by hythl0day** [comment]
Thanks. This is an open source project you can do whatever you want with my code.
Of course, I would appreciate it If you could leave a reference link to this GitHub page.

I'm happy to put this to more tests on production usage. Feel free to ask me if there's any question or needs.

And in the end, please don't use issue function to raise this kind of question. I will close this since it's not about bugs or requirements about this project.

**Comment by polotto** [comment]
Thank you! How can contact you besides here?

**Comment by hythl0day** [comment]
> 

you can email me: chengfubeiming@live.com
or you can use discord, the discord link is in the readme.

**Comment by hythl0day** [comment]
By the way, I looked again at the example, and I found a little bug regarding string escaping. the '\'' in the string is not handled correctly, I'll fix it quickly with a new commit.

**Comment by polotto** [comment]
Yes, I saw this, the scape was ignored by the compiler.

How is pronounced Hetu?

**Comment by hythl0day** [comment]
> Yes, I saw this, the scape was ignored by the compiler.
> 
> How is pronounced Hetu?

It's a Chinese word, should be pronounced like 'hatwo', where 'ha' in 'Hawaii'. However, you can pronounce it the way you like. It's not very important.
